spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

springdoc.swagger-ui.path: /swagger-ui.html

logging:
  level:
    com.nubiform: debug

jwt:
  header: Authorization
  secret: c3ByaW5nLXNlY3VyaXR5LXJlc3QtbG9naW4tYnktbnViaWZvcm0=
  token-validity-in-second: 1800