spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: ture

springdoc.swagger-ui.path: /swagger-ui.html
logging:
  level:
    com.nubiform: debug